### ISSUE TITLE
GameListManager  7.1b is crashing at startup

### ISSUE THREAD

**Issue by zestef** [RobG66/Gamelist-Manager#9]
**What :** When I launch the latest version (7.1b) of the "gamelistmanager.exe" application, it opens and closes quickly.
**Where :** Operating System: Windows 11 24H2 FR / .Net Framework 4.8.1 up to date
**More details :** I have the following elements in the event log (application)

---------------------------------------------------------
Application: GamelistManager.exe
CoreCLR Version: 8.0.1024.46610
.NET Version: 8.0.10
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException: 'lastfile_gamelist - Copie' n'est pas une valeur valide pour la propriété 'Name'.
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   at GamelistManager.MainWindow.AddRecentFilesToMenu() in C:\Users\losti\Source\Repos\Gamelist-Manager\MainWindow.xaml.cs:line 572
   at GamelistManager.MainWindow.Window_Loaded(Object sender, RoutedEventArgs e) in C:\Users\losti\Source\Repos\Gamelist-Manager\MainWindow.xaml.cs:line 617
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.Resize(ICompositionTarget resizedCompositionTarget)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

--------------------------------------------
(Sorry this one is partially in french) : 
Nom de l'application défaillante : GamelistManager.exe, version : 1.0.0.0, horodatage : 0x66e80000
Nom du module défaillant : KERNELBASE.dll, version : 10.0.26100.2161, horodatage : 0x31da495c
Exception code: 0xe0434352
Fault offset: 0x00000000000c831a
Identifiant du processus défaillant : 0x1A014
Heure de début de l'application défaillante : 0x1DB2EF65479BA87
Chemin de l'application défaillante : C:\Users\steph\OneDrive\Downloads\GamelistManager\GamelistManager.exe
Chemin du module défaillant : C:\WINDOWS\System32\KERNELBASE.dll
ID du rapport : c1b22da7-1cef-45ae-8e42-11a8aa802ce3
Nom complet du package défaillant : 
Package défaillant – ID d'application relatif :

**Comment by zestef** [comment]
No issue with 6.1 version (and the previous 7.0 beta)

**Comment by RobG66** [comment]
Try renaming the folder %AppData\Local\GamelistManager

 to something like gamelistmanager-old

 This is where all settings are saved now.  Perhaps upload the user.config within the folder structure so I can test it to see what the issue is.

**Comment by RobG66** [comment]
Looks like WPF doesn't like spaces in  the menu item name field.  I'll make a filter for that.  In the meantime, my suggestion will at least get it working for you.  I will also post a fix shortly

**Comment by zestef** [comment]
Media management is on my to-do list, but it's a lot of work to implement so it just takes time.
